### ISSUE TITLE
This site can’t be reached X.X.X.X refused to connect.

### ISSUE THREAD

**Issue by johnnymueller** [me-vlad/wse-plugin-reloadschedule#1]
I've successfully compiled from this source code, I've put HTTPReloadSchedule.jar in [WSE]/lib restarted the server, and followed the directions for adding a VHost.xml but  I'm now getting the following error: "This site can’t be reached X.X.X.X refused to connect." I'm also not seeing anything in the Wowza error log.

Do you have any thoughts on what could be going wrong? I'm on WSE 4.7.6, which version were you able to get this working on?

Thanks

**Comment by me-vlad** [comment]
Please check that wowza http provider listening on tcp port 8086 and not filtered by firewall.

**Comment by johnnymueller** [comment]
Thanks @me-vlad, the issue was that I was compiling against JDK 10 and the version of Wowza we are using was compiled with 7 or 8.

**Comment by me-vlad** [comment]
Hi @johnnymueller , you can also use precompiled module from release page:
https://github.com/me-vlad/wse-plugin-reloadschedule/releases/download/v1.0.0/wse-plugin-reloadschedule-1.0.0.tar.gz
